### ISSUE TITLE
Web font support in svg backend

### ISSUE THREAD

**Issue by fcooper8472** [martinjrobins/trase#20]
Would be good to optionally link-in web fonts (such as [Google fonts](https://fonts.google.com/)) when using the SVG backend.

This will require:
1. A method to add an attribute to the svg such as:
```xml
<style type="text/css">
    @import url('https://fonts.googleapis.com/css?family=Indie+Flower');
</style>
```
2. The ability to change the font wherever fonts are passed in to the backend (currently just in `Axis::draw_common`.  This might be best as a method on the axis class that fills in a new member variable on the axis class.

**Comment by martinjrobins** [comment]
Closed via PR #22
