### ISSUE TITLE
Add encoding information to svg serialization

### ISSUE THREAD

**Issue by fcooper8472** [martinjrobins/trase#21]
Here's a useful tool that can determine SVG standards compliance:
https://validator.w3.org/

Currently the test svg is missing encoding information, which should simply look something like 
`encoding="utf-8"` in the document header.

Matplotlib's first line in SVG docs is
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
```
trase currently has
```xml
<?xml version="1.0" standalone="no"?>
```

**Comment by martinjrobins** [comment]
Great, good catch. Can we use this validator via the command line? Be nice to add it to the automated testing to check that a valid svg file is output by the `BackendSVG` test

**Comment by fcooper8472** [comment]
Looks as though this might be of use:
https://github.com/validator/validator

> vnu.jar is a portable standalone version for batch-checking documents from the command line and from other scripts/apps, or for deploying the checker as a self-contained service

**Comment by martinjrobins** [comment]
Yes, that could be useful! I made a new issue for this, closing this as done
